defaults:
  - default
  - _self_

ds_path: '/Users/martin/datasets/fineweb_gpt2_2p5B.bin'
num_eval_tokens: 5_000
eval_every_tokens: 10_000
# ckpt_restore_path: 'weights/1_87'
wandb_project: 'picodo-local'
wandb_mode: 'offline'

model:
  D: 32
  H: 2
  L: 128
  N: 3
  F: 128

opt:
  train_microbatch_size: 8
  eval_batch_size: 8
  grad_accumulation_steps: "0:1;10_000:5;50_000:10"
  adam_t1: 1_000
  adam_t2: 1_000_000
  num_train_tokens: 100_000
